--Identify Bologna's team ID listed in the teams_italy table by selecting the team_long_name and team_api_id.
-- Select team_long_name and team_api_id from team
SELECT
	team_long_name,
	team_api_id
FROM teams_italy
-- Filter for team long name
WHERE team_long_name = 'Bologna';

--------------------------------------------------------------
--query result
team_long_name	team_api_id
Bologna	9857
-------------------------------------------------------------
--Select the season and date that a match was played.
--Complete the CASE statement so that only Bologna's home and away wins are identified.
-- Select the season and date columns
SELECT 
	season,
	date,
    -- Identify when Bologna won a match
	CASE WHEN hometeam_id = 9857 
        AND home_goal > away_goal 
        THEN 'Bologna Win'
		WHEN awayteam_id = 9857 
        AND away_goal > home_goal 
        THEN 'Bologna Win' 
		END AS outcome
FROM matches_italy;

-------------------------------------------------------------
--query result
season	date	outcome
2011/2012	2011-12-20	null
2011/2012	2011-12-21	null
2011/2012	2011-10-30	Bologna Win
2011/2012	2011-10-30	null
2011/2012	2011-10-29	null
2011/2012	2011-10-30	null
2011/2012	2011-10-29	null
-------------------------------------------------------------
--Select the home_goal and away_goal for each match.
--Use the CASE statement in the WHERE clause to filter all NULL values generated by the statement in the previous step.
-- Select the season, date, home_goal, and away_goal columns
SELECT 
	season,
    date,
	home_goal,
	away_goal
FROM matches_italy
WHERE 
-- Exclude games not won by Bologna
	CASE WHEN hometeam_id = 9857 AND home_goal > away_goal THEN 'Bologna Win'
		WHEN awayteam_id = 9857 AND away_goal > home_goal THEN 'Bologna Win' 
		END IS NOT NULL;

----------------------------------------------------------------
--query result
matches_italy
teams_italy
season	date	home_goal	away_goal
2011/2012	2011-10-30	3	1
2011/2012	2011-12-04	1	0
2011/2012	2012-01-08	2	0
2011/2012	2012-02-21	2	0
2011/2012	2012-02-17	0	3
2011/2012	2012-04-12	1	0
